// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pouxehyvczyzbkwapghd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvdXhlaHl2Y3p5emJrd2FwZ2hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDE0ODIsImV4cCI6MjA2NDQxNzQ4Mn0.i9z3Diarw1rhWlgeURCGyti2YdCaUtO0opNdLgkRXdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);